service: update-city-info

plugins:
  - serverless-localstack
  - serverless-plugin-typescript

provider:
  name: aws
  stage: local
  region: eu-central-1
  runtime: nodejs18.x
  stackName: update-info      
  credentials:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode: True

functions:
  update-city-info:
    handler: ./handler.ts
    name: update-info
    description: A microservice to updade city info
    timeout: 300
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true


